name: Fetch Repo After Push

# Controls when the action will run. 
on:
  push:
    branches:
      - main
      - test
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Make request to thomaswsmith for IP detection
        run: curl https://www.thomaswsmith.com/

      - name: Install Python packages
        run: pip install -r requirements.txt

      # It would be nice to get rid of this step entirely once SnowCLI supports using only env variables
      - name: Configure SnowCLI
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}

        run: |
          ifconfig
          cd $GITHUB_WORKSPACE
          echo "[connections]" > connections.toml
          echo "[connections.default]" >> connections.toml
          echo "account = \"$SNOWFLAKE_ACCOUNT\"" >> connections.toml
          chown $USER "/home/runner/work/ci_cd_streamlit/ci_cd_streamlit/connections.toml"
          chmod 0600 "/home/runner/work/ci_cd_streamlit/ci_cd_streamlit/connections.toml"

      - name: Fetch Repo Using Creds in Env Variables
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_CONNECTIONS_DEV_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: |
          snow --config-file $GITHUB_WORKSPACE/connections.toml sql -q "ALTER GIT REPOSITORY cicd_streamlit_app FETCH"
