# GitLab CI/CD Pipeline

stages:
  - deploy

variables:
  PYTHON_VERSION: "3.10"

deploy:
  stage: deploy
  image: python:${PYTHON_VERSION}-slim
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - when: manual
  script:
    - apt-get update && apt-get install -y curl python3 python3-pip
    - pip install -r requirements.txt
    - echo "[connections]" > connections.toml
    - echo "[connections.default]" >> connections.toml
    - echo "account = \"$SNOWFLAKE_ACCOUNT\"" >> connections.toml
    - echo "database = \"$SNOWFLAKE_DATABASE\"" >> connections.toml
    - echo "schema = \"$SNOWFLAKE_SCHEMA\"" >> connections.toml
    - echo "warehouse = \"$SNOWFLAKE_WAREHOUSE\"" >> connections.toml
    - chmod 0600 "connections.toml"
    - cat connections.toml
    - echo "$SNOWFLAKE_ACCOUNT"

    - snow --config-file connections.toml sql -q "ALTER GIT REPOSITORY cicd_streamlit_app_gitlab FETCH"
  environment:
    name: production
  artifacts:
    paths:
      - connections.toml
    expire_in: 1 week
